### ISSUE TITLE
Where is the token validator that it says is in Discord Console Hacks?

### ISSUE THREAD

**Issue by Anonymous941** [hxr404/Discord-Oxygen#10]
> * Token Cracker & Validator (I reversee-engineered Discords JWT System, check out [Discord Console Hacks](https://github.com/hxr404/Discord-Console-hacks))
I don't see anything about this in that repo.  Where is it?

**Comment by hxr404** [comment]
Discord Oxygen is not released yet, so obviously you can't download the token validator either.
(Its included in Discord Oxygen, they aren't separate programs)
