### ISSUE TITLE
Is this going to happen?

### ISSUE THREAD

**Issue by coolman3289** [hxr404/Discord-Oxygen#14]
How far are you into the project? To me it seems like a great concept, but I don’t think it’s happening. I want to help, but I do not give money to something that will never happen (this happened before)

**Comment by coolman3289** [comment]
Do you have any progress at all? Like any of the features? This seems impossible, or at least extremely hard. You have some sponserers, but it seems that this project is not going to go anywhere.

**Comment by arnobarton** [comment]
Any updates on the progress of this project ?

**Comment by Anonymous941** [comment]
@hxr404 Do you have _any_ code?  If so, can you post it here?

**Comment by hxr404** [comment]
> @hxr404 Do you have _any_ code? If so, can you post it here?

I do. And if you read the FAQ, you'd know that I can't and won't post it publically here or anywhere else.

**Comment by hxr404** [comment]
To answer OP's question: Yes, this is going to happen. Slowly, but steadily I'm making progress. For further discussions please make use of GitHubs "Discussions" tab or join the community on matrix.

**Comment by Anonymous941** [comment]
> > @hxr404 Do you have _any_ code? If so, can you post it here?
> 
> I do. And if you read the FAQ, you'd know that I can't and won't post it publically here or anywhere else.

I understand, but what about client-only modifications?  Those can't be patched by Discord.

**Comment by hxr404** [comment]
> > > @hxr404 Do you have _any_ code? If so, can you post it here?
> > 
> > 
> > I do. And if you read the FAQ, you'd know that I can't and won't post it publically here or anywhere else.
> 
> I understand, but what about client-only modifications? Those can't be patched by Discord.

Client-only doesn't mean it doesn't depend on Discord's code. Take for example the script to view hidden channels. If Discord would stop delivering the data to the client it couldn't be displayed by the hacks anymore. Also this isn't the only reason I can't publish the source code (again check the FAQ).

**Comment by hxr404** [comment]
> For further discussions please make use of GitHubs "Discussions" tab or join the community.
