### ISSUE TITLE
Release when?

### ISSUE THREAD

**Issue by Apoc101** [hxr404/Discord-Oxygen#24]

**Comment by hxr404** [comment]
From README:
![image](https://user-images.githubusercontent.com/55095883/171878316-69b7eb26-c844-4fb4-9e02-81867c482598.png)

see the [FAQ](https://github.com/hxr404/Discord-Oxygen/blob/main/FAQ.md)

**Comment by Anonymous941** [comment]
Never, this project is obviously not going to be made.

**Comment by Anonymous941** [comment]
> > Never, this project is obviously not going to be made.
> 
>     1. Stop Necroposting
> 
>     2. Why are you even here if you really believe this?
>        I can assure you I'd publicly announce if Discord Oxygen were to be discontinued. And as long as I don't do that, this project _is_ gonna be made. If you don't believe me than do me a favor and stop wasting your and my time.

Then why has it been so long and you can't even give a screenshot or release date?

**Comment by Apoc101** [comment]
> > > Never, this project is obviously not going to be made.
> > 
> > 
> > ```
> > 1. Stop Necroposting
> > 
> > 2. Why are you even here if you really believe this?
> >    I can assure you I'd publicly announce if Discord Oxygen were to be discontinued. And as long as I don't do that, this project _is_ gonna be made. If you don't believe me than do me a favor and stop wasting your and my time.
> > ```
> 
> Then why has it been so long and you can't even give a screenshot or release date?

Cause either he cares about secrecy to the point of disappointing his fans, or he's just not being transparent about the project's state of development.

**Comment by hxr404** [comment]
Since this issue seems to get some attention recently I decided to comment on this.
About the release date, I'm tired of repeating that I can't give any ETA. Please refer to the FAQ.
About not posting screenshots:
I have very limited time working on this project, I rather use it to get things done instead of documenting some GUI stuff. As with most things in IT, the GUI is just the tip of the iceberg. Most of the work happens under the hood. And due to the secretive nature of this project I can't provide any insights to what's happening under the hood.

**Comment by Anonymous941** [comment]
> Since this issue seems to get some attention recently I decided to comment on this. About the release date, I'm tired of repeating that I can't give any ETA. Please refer to the FAQ. About not posting screenshots: I have very limited time working on this project, I rather use it to get things done instead of documenting some GUI stuff. As with most things in IT, the GUI is just the tip of the iceberg. Most of the work happens under the hood. And due to the secretive nature of this project I can't provide any insights to what's happening under the hood.

Why are you so secretive?  Seriously, why??

**Comment by Anonymous941** [comment]
> > Since this issue seems to get some attention recently I decided to comment on this. About the release date, I'm tired of repeating that I can't give any ETA. Please refer to the FAQ. About not posting screenshots: I have very limited time working on this project, I rather use it to get things done instead of documenting some GUI stuff. As with most things in IT, the GUI is just the tip of the iceberg. Most of the work happens under the hood. And due to the secretive nature of this project I can't provide any insights to what's happening under the hood.
> 
> Why are you so secretive? Seriously, why??

@hxr404 No response, I'm unfollowing.  Enough is enough.

**Comment by hxr404** [comment]
> > > Since this issue seems to get some attention recently I decided to comment on this. About the release date, I'm tired of repeating that I can't give any ETA. Please refer to the FAQ. About not posting screenshots: I have very limited time working on this project, I rather use it to get things done instead of documenting some GUI stuff. As with most things in IT, the GUI is just the tip of the iceberg. Most of the work happens under the hood. And due to the secretive nature of this project I can't provide any insights to what's happening under the hood.
> > 
> > 
> > Why are you so secretive? Seriously, why??
> 
> @hxr404 No response, I'm unfollowing. Enough is enough.

I'm not obliged in any way to reply to your questions. After all, this is a hobby project I maintain during my (nonexistent) free time.
If your "questions" would be real questions and not just random tormenting, I'd answer them.
What am I supposed to reply to things like _"Never, this project is obviously not going to be made."_? The only thing I could do in response is to simply block you to stop you from wasting my time.
So either you really move-on and unfollow, or you start making actual contributions to the discussion here (to which profound replies are actually possible) or I'll really have to block you. It's up to you, but I personally don't have the time and energy to deal with people acting like kids.

**Comment by hxr404** [comment]
Locking this, as this is obviously leading nowhere.
