### ISSUE TITLE
seek help

### ISSUE THREAD

**Issue by Vap0r1ze** [hxr404/Discord-Oxygen#33]
seek help

**Comment by arandomhooman** [comment]
What does this mean?

**Comment by hxr404** [comment]
@Vap0r1ze please provide more details or ask your questions in the appropiate community channels.

**Comment by Vap0r1ze** [comment]
> @Vap0r1ze please provide more details or ask your questions in the appropiate community channels.

Seek help

**Comment by hxr404** [comment]
u good?

**Comment by Staleyy** [comment]
this guy taking drugs

**Comment by patrickTs70** [comment]
How do I download beta

**Comment by hummusaki** [comment]
You can't its a fake project

**Comment by legaldusty** [comment]
yeah that really sucks tho, I have been waiting for a while for this... But damn, I guess it is fake isn't it.

**Comment by AerixBlox** [comment]
lol

**Comment by hxr404** [comment]
@Vap0r1ze 
> seek help

hope you got the help you were seeking in the meantime

@Staleyy
> this guy taking drugs

oh well funny thing, used to do that too

@Apoc101 
> You can't its a fake project

Nope not fake, just discontinued, I get why you'd think so though

@TrueRetr0 
> yeah that really sucks tho, I have been waiting for a while for this... But damn, I guess it is fake isn't it.

sorry for the disappointment -.-
anyways here's the remains of the source code: https://github.com/Discord-Oxygen/Discord-Oxygen-source
