### ISSUE TITLE
Hey, may i know when is this gonna release or is there beta available?

### ISSUE THREAD

**Issue by vox-danger** [hxr404/Discord-Oxygen#36]
Hey, may i know when is this gonna release or is there beta available?
i can try it and report bugs and more.

**Comment by Raz-js** [comment]
Bro its been 3 years without a trace of effort or development, its a dead project that has been dragged out and probably never existed in the first place

**Comment by Anonymous941** [comment]
> Bro its been 3 years without a trace of effort or development, its a dead project that has been dragged out and probably never existed in the first place

Finally, someone else agrees!  I thought it was just me who thought this was a scam for attention.

**Comment by hummusaki** [comment]
Everything this dude does is a scam for attention. If you check his discord server/matrix bridge its a complete joke. He's not accepting help from anyone nor is he sharing any info on the project (because it's a sham), so just give up on it before you get your hopes up.

**Comment by THEJON78** [comment]
Ask fiber modem. You know what, DM me on discord for my DMs with fiber modem to see the truth. my discord is "thefrenchfrysecret".

**Comment by Anonymous941** [comment]
> Ask fiber modem. You know what, DM me on discord for my DMs with fiber modem to see the truth. my discord is "downwithdisc0rd".

What?

**Comment by THEJON78** [comment]
> > Ask fiber modem. You know what, DM me on discord for my DMs with fiber modem to see the truth. my discord is "downwithdisc0rd".
> 
> What?

Fiber modem was a past dev.

**Comment by CreeperGamerGitHub** [comment]
oh yeah its thefrenchfrysecret now

**Comment by Anonymous941** [comment]
> Fiber modem was a past dev.

Okay, what's the truth?

**Comment by ThatOneCreeperGamerGithub** [comment]
> > Fiber modem was a past dev.
> 
> Okay, what's the truth?

Okay, alt time.
She said there is no ETA, Code, or any of it. She even got muted on her alt (on a prev disc) for possible alt.
HXR is just covering everything up. don't believe him. i'll even see if i can find the dms.

**Comment by THEJON78** [comment]
thats my alt

**Comment by Anonymous941** [comment]
> She said there is no ETA, Code, or any of it ... HXR is just covering everything up

That's what I expected, but why is HXR covering it up?  To get donations to a fake project?

> thats my alt

Do you mind posting the full story here?  HXR clearly isn't watching...

---

Also what's interesting is when I ran [astronomer](https://github.com/Ullaakut/astronomer) (a tool to detect fake stars), I got a very bad rating, indicating that this is a scam:

```
Averages                             Score           Trust
--------                             -----           -----
Weighted contributions:              5817              D
Private contributions:               555               A
Created issues:                      11                D
Commits authored:                    874               A
Repositories:                        22                C
Pull requests:                       10                D
Code reviews:                        1                 E
Account age (days):                  1325              C
5th percentile:                      0                 E
10th percentile:                     4                 E
15th percentile:                     21                C
20th percentile:                     36                D
25th percentile:                     58                D
30th percentile:                     96                D
35th percentile:                     138               D
40th percentile:                     250               D
45th percentile:                     394               C
50th percentile:                     700               C
55th percentile:                     1004              C
60th percentile:                     1375              C
65th percentile:                     1750              D
70th percentile:                     2176              D
75th percentile:                     3198              D
80th percentile:                     4866              D
85th percentile:                     5653              D
90th percentile:                     9197              D
95th percentile:                     20043             D
----------------------------------------------------------
Overall trust:                                         D
```

**Comment by THEJON78** [comment]
> > She said there is no ETA, Code, or any of it ... HXR is just covering everything up
> 
> That's what I expected, but why is HXR covering it up? To get donations to a fake project?
> 
> > thats my alt
> 
> Do you mind posting the full story here? HXR clearly isn't watching...
> 
> Also what's interesting is when I ran [astronomer](https://github.com/Ullaakut/astronomer) (a tool to detect fake stars), I got a very bad rating, indicating that this is a scam:
> 
> ```
> Averages                             Score           Trust
> --------                             -----           -----
> Weighted contributions:              5817              D
> Private contributions:               555               A
> Created issues:                      11                D
> Commits authored:                    874               A
> Repositories:                        22                C
> Pull requests:                       10                D
> Code reviews:                        1                 E
> Account age (days):                  1325              C
> 5th percentile:                      0                 E
> 10th percentile:                     4                 E
> 15th percentile:                     21                C
> 20th percentile:                     36                D
> 25th percentile:                     58                D
> 30th percentile:                     96                D
> 35th percentile:                     138               D
> 40th percentile:                     250               D
> 45th percentile:                     394               C
> 50th percentile:                     700               C
> 55th percentile:                     1004              C
> 60th percentile:                     1375              C
> 65th percentile:                     1750              D
> 70th percentile:                     2176              D
> 75th percentile:                     3198              D
> 80th percentile:                     4866              D
> 85th percentile:                     5653              D
> 90th percentile:                     9197              D
> 95th percentile:                     20043             D
> ----------------------------------------------------------
> Overall trust:                                         D
> ```

aight one sec lemme look

**Comment by steinhorror** [comment]
To clear things up:
Fiber Modem is my alt (you can dm me @fibermodem). I was interested in starting my own kind of modules that do stuff like Nitro as far as possible. Once i found out hxr also did such a project i decided that rather than one person doing stuff alone, we could both do this project to get more progress faster. So i coded some stuff, made the logo and name. But once i didn't see a lot of progress from hxr and instead only more links to support him financially, i decided to leave. And with Discord doing more and more to get money out of you without significant features i stopped with modules.

**Comment by dxcvvxd** [comment]
> To clear things up: Fiber Modem is my alt (you can dm me @fibermodem). I was interested in starting my own kind of modules that do stuff like Nitro as far as possible. Once i found out hxr also did such a project i decided that rather than one person doing stuff alone, we could both do this project to get more progress faster. So i coded some stuff, made the logo and name. But once i didn't see a lot of progress from hxr and instead only more links to support him financially, i decided to leave. And with Discord doing more and more to get money out of you without significant features i stopped with modules.

thanks for clearing things up, i found about this projects in 2022 and it felt genuine but now i see that it just isnt
and some of the features listed are easily available using other 3rd party clients
so bro is just yapping, nothing is being actually done

**Comment by THEJON78** [comment]
> To clear things up: Fiber Modem is my alt (you can dm me @fibermodem). I was interested in starting my own kind of modules that do stuff like Nitro as far as possible. Once i found out hxr also did such a project i decided that rather than one person doing stuff alone, we could both do this project to get more progress faster. So i coded some stuff, made the logo and name. But once i didn't see a lot of progress from hxr and instead only more links to support him financially, i decided to leave. And with Discord doing more and more to get money out of you without significant features i stopped with modules.

oh hi fiber!

**Comment by AerixBlox** [comment]
damn

**Comment by hxr404** [comment]
Project discontinued. Sorry.
Check out it's remains if you want https://github.com/Discord-Oxygen/Discord-Oxygen-source

or don't and move on to a platform that's actually not as shitty as discord.

**Comment by hxr404** [comment]
btw @steinhorror hi, thank you and farewell
